[package]
name = "async-pop3"
version = "0.1.0"
edition = "2021"

[dependencies]
async-native-tls = {version = "0.4.0", default-features = false, features = ["runtime-tokio"] }
tokio = { version = "1.26.0", features = ["net", "time", "rt", "macros"] }

[dev-dependencies]
dotenv = "0.15"

