[package]
name = "pop3"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features=["derive"] }
serde_json = { version = "1.0", optional = true }

native-tls = "0.2"
bufstream = "0.1"
either = "1.8"

[dev-dependencies]
dotenv = "0.15"

[features]
json = ["dep:serde_json"]