version: '3.3'

services:
    standalone:
        ports:
            - '3025:3025'
            - '3110:3110'
            - '3143:3143'
            - '3465:3465'
            - '3993:3993'
            - '3995:3995'
        image: 'greenmail/standalone:1.6.12'