kind: pipeline
type: docker
name: test-pop

platform:
  os: linux
  arch: amd64

services:
  - name: greenmail
    image: 'greenmail/standalone:1.6.12'
    environment:
      GREENMAIL_OPTS: "-Dgreenmail.verbose -Dgreenmail.setup.test.pop3 -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.users=test:localhost"

steps:
  - name: Run pop3 tests
    image: rust:1.61
    pull: if-not-exists
    volumes:
      - name: cache
        path: /drone/src/target
    environment:
      SERVER: "greenmail"
      PORT: "3110"
      USERNAME: "test"
      PASSWORD: "localhost"
    commands:
      - cargo fetch --locked
      - cargo test --package pop3

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache/dust-mail/target

---
kind: pipeline
type: docker
name: test-autoconfig

platform:
  os: linux
  arch: amd64

steps:
  - name: Run autoconfig tests
    image: rust:1.61
    pull: if-not-exists
    volumes:
      - name: cache
        path: /drone/src/target
    commands:
      - cargo fetch --locked
      - cargo test --package autoconfig

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache/dust-mail/target