[workspace]

members = [
    "apps/web/src-tauri",
    "packages/sdk",
    "packages/autoconfig",
    "packages/pop3"
]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
strip = true 
opt-level = "s"