[workspace]

members = [
    "apps/web/src-tauri",
    "apps/server",
    "packages/sdk",
    "packages/async-tcp",
    "packages/autoconfig",
    "packages/structures-rs",
    "packages/async-pop3"
]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
strip = true 
opt-level = "s"