port = 8080
host = "0.0.0.0"
behind_proxy = false

[rate_limit]
max_queries = 8
time_span = 10

[appearance]
name = "Dust-Mail-server"
description = "A Dust-Mail backend server"

[cache]
timeout = 300

[auth]
secret = "RU0EcqdiDC7KKGYVx003MW3xDFubAdwE"
type = "password"

[auth.password]
password = "aSJE8XN5boaiWiHgsn4960o4vQp7Z8on"
