[package]
name = "sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Imap
imap = {version = "2.4.1", optional = true }
imap-proto = { version = "0.16", optional = true }
bufstream = {version = "0.1", optional = true}

# Pop
pop3 = {version = "0.1", optional = true, path = "../pop3" }

# Smtp
lettre = { version = "0.10", optional = true }

# Autodetect service
autoconfig = {version = "0.1", optional = true, path = "../autoconfig" }

# Generic mail utilities
mailparse = "0.14"

# Serde
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Time
chrono = "0.4"

# Tls
native-tls = "0.2"

# Async
tokio = { version = "1", features = ["full"] }
futures = "0.3"

# Sanitizing text
ammonia = "3"

[dev-dependencies]
dotenv = "0.15.0"

[features]
default = ["imap", "pop", "detect", "smtp"]

detect = ["autoconfig"]
autoconfig = ["dep:autoconfig"]

smtp = ["dep:lettre"]

pop = ["dep:pop3"]
imap = ["dep:imap", "dep:imap-proto", "dep:bufstream"]
