[package]
name = "sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imap = {version = "2.4.1", optional = true }
imap-proto = { version = "0.16", optional = true }
pop3 = {version = "0.1", optional = true, path = "../pop3", features = ["json"] }
autoconfig = {version = "0.1", optional = true, path = "../autoconfig" }
bufstream = {version = "0.1", optional = true}
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
native-tls = "0.2"
mailparse = "0.14"
tokio = { version = "1", features = ["full"] }
futures = "0.3"

[dev-dependencies]
dotenv = "0.15.0"

[features]
default = ["imap", "pop", "detect"]

detect = ["autoconfig"]
autoconfig = ["dep:autoconfig"]

pop = ["dep:pop3"]
imap = ["dep:imap", "dep:imap-proto", "dep:bufstream"]
