[package]
name = "autoconfig"
authors = ["Guus van Meerveld"]
description = "A simple implementation of Mozilla Thunderbird's autoconfig"
readme = "README.md"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde-xml-rs = "0.6"
serde = {version = "1.0", features = ["derive"] }

dust-mail-utils = { version = "0.1.0", path = "../structures-rs" }

tokio = { version = "1.26.0", features = ["net", "time", "rt", "macros"] }
futures = "0.3.27"
reqwest = "0.11.16" 
