[package]
name = "autoconfig"
authors = ["Guus van Meerveld"]
description = "A simple implementation of Mozilla Thunderbird's autoconfig"
readme = "README.md"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde-xml-rs = "0.6"
serde = {version = "1.0", features = ["derive"] }
regex = "1.7"
reqwest = { version = "0.11", features = ["blocking"] }