[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imap = {version = "2.4.1", optional = true }
imap-proto = { version = "0.16", optional = true }
pop3 = {version = "0.1.0", optional = true, path = "../pop3" }
chrono = "0.4"
native-tls = "0.2"
mailparse = "0.14.0"

[dev-dependencies]
dotenv = "0.15.0"

[features]
default = ["imap", "pop"]
pop = ["dep:pop3"]
imap = ["dep:imap", "dep:imap-proto"]