name: Deploy Standalone

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-standalone.yml
      - Dockerfile
      - entrypoint.sh
      - nginx/**
      - .dockerignore
      - packages/server/**
      - packages/client/**

jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Build and push to Docker hub
        uses: guusvanmeerveld/actions/docker@main
        with:
          username: guusvanmeerveld
          token: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: guusvanmeerveld/dust-mail:git-standalone
          platforms: linux/amd64,linux/arm64
