name: Test and deploy all apps

on:
  push:
    branches:
      - main
    paths:
      - apps/server/**
      - .github/workflows/deploy-commit.yml
      - Dockerfile
      - entrypoint.sh
      - nginx/**
      - .dockerignore
      - apps/**
      - packages/**

jobs:
  test:
    name: Test apps
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Setup
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "pnpm"

      - name: Install NPM dependencies
        run: pnpm install --prefer-offline

      - name: Run full suite
        run: pnpm run deploy

  build-base:
    name: Build Docker base image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base image
        uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/guusvanmeerveld/dust-mail:base
          context: .
          file: Dockerfile.base
          platforms: linux/amd64,linux/arm64

  build-apps:
    name: Build Docker apps images
    needs: build-base
    runs-on: ubuntu-latest

    strategy:
      matrix:
        type: [server, client]

    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build server image
        uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/guusvanmeerveld/dust-mail:git-${{ matrix.type }}
          context: .
          file: apps/${{ matrix.type }}/Dockerfile
          platforms: linux/amd64,linux/arm64

  build-standalone:
    name: Build Docker standalone image
    needs: build-base
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build server image
        uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/guusvanmeerveld/dust-mail:git-standalone
          context: .
          file: /Dockerfile
          platforms: linux/amd64,linux/arm64
