name: Deploy Server

on:
  push:
    branches:
      - main
    paths:
      - packages/server/**
      - .github/workflows/deploy-server.yml

jobs:
  test:
    name: Test server
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: "yarn"

      - name: Install NPM dependencies
        run: yarn --cwd packages/server install

      - name: Build server
        run: yarn --cwd packages/server run build

      # - name: Run normal tests
      #   run: yarn --cwd packages/server run test

      # - name: Run end-to-end tests
      #   run: yarn --cwd packages/server run test:e2e

  heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Push to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dust-mail"
          heroku_email: "${{secrets.HEROKU_EMAIL}}"
          appdir: "packages/server"

  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: linux/amd64, linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: guusvanmeerveld
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & Push
      - name: Build Dockerfile and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: packages/server

          tags: guusvanmeerveld/dust-mail:server
          platforms: linux/amd64, linux/arm64

          # Cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
