name: Deploy to Github Pages / Docker hub

on:
  push:
    branches:
      - main
    paths:
      - packages/client
      - .github/workflows/deploy-client.yml

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Install NPM dependencies
        run: yarn install

      - name: Check size
        run: yarn --cwd packages/client run size
        env:
          BASE_URL: "/Mail-Client"

      - name: Deploy to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/client/dist

  docker:
    runs-on: ubuntu-latest
    needs: pages
    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: guusvanmeerveld
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & Push
      - name: Build Dockerfile and push
        uses: docker/build-push-action@v2
        with:
          context: packages/client
          push: true
          tags: guusvanmeerveld/mail-client:latest

          # Cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
