name: Deploy Client

on:
  push:
    branches:
      - main
    paths:
      - packages/client/**
      - .github/workflows/deploy-client.yml

jobs:
  pages:
    name: Build pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Install NPM dependencies
        run: yarn --cwd packages/client install

      - name: Build client
        run: yarn --cwd packages/client run build --base=/Dust-Mail/
        env:
          VITE_DEFAULT_SERVER: https://dust-mail.herokuapp.com

      - name: Check size
        run: yarn --cwd packages/client run size

      - name: Deploy to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/client/dist

  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: pages
    steps:
      - name: Setup
        uses: actions/checkout@v2

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1.2.0
      #   with:
      #     platforms: linux/amd64, linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: guusvanmeerveld
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & Push
      - name: Build Dockerfile and push
        uses: docker/build-push-action@v2
        with:
          context: packages/client
          push: true

          tags: guusvanmeerveld/dust-mail:client
          # platforms: linux/amd64, linux/arm64

          # Cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
