name: Test and deploy all apps

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/deploy-commit.yml
      - fly.toml
      - Dockerfile
      - entrypoint.sh
      - pnpm-lock.yaml
      - Cargo.lock
      - nginx/**
      - .dockerignore
      - apps/web/**
      - apps/server/**
      - packages/**

jobs:
  test-pop: 
    name: Test Pop3 Package
    runs-on: ubuntu-latest


    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.61
          default: true
          override: true

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./packages/pop3

      - name: Fetch crates
        working-directory: ./packages/pop3
        run: cargo fetch --locked

      - name: Start Greenmail
        run: docker-compose -f packages/pop3/docker-compose.test.yml up -d

      - name: Test package
        working-directory: ./packages/pop3
        run: cargo test

  test:
    name: Test apps
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Setup
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "pnpm"

      - name: Install NPM dependencies
        run: pnpm install --prefer-offline --ignore-scripts

      - name: Run full suite
        run: pnpm run deploy --filter @dust-mail/web --filter @dust-mail/server

  build-apps:
    name: Build Docker apps images
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        type: [server, web]

    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: guusvanmeerveld
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build app image
        uses: docker/build-push-action@v3
        with:
          tags: |
            guusvanmeerveld/dust-mail:git-${{ matrix.type }}
            ghcr.io/guusvanmeerveld/dust-mail:git-${{ matrix.type }}

          push: true

          context: .
          file: apps/${{ matrix.type }}/Dockerfile

          platforms: linux/amd64,linux/arm64

          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-standalone:
    name: Build Docker standalone image
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: guusvanmeerveld
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build standalone image
        uses: docker/build-push-action@v3
        with:
          tags: |
            guusvanmeerveld/dust-mail:git-standalone
            ghcr.io/guusvanmeerveld/dust-mail:git-standalone

          push: true

          context: .
          file: Dockerfile

          platforms: linux/amd64,linux/arm64

          cache-from: type=gha
          cache-to: type=gha,mode=max
