name: Test and deploy all apps

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/deploy-commit.yml
      - fly.toml
      - Dockerfile
      - entrypoint.sh
      - pnpm-lock.yaml
      - nginx/**
      - .dockerignore
      - apps/**
      - packages/**

jobs:
  test:
    name: Test apps
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Setup
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "pnpm"

      - name: Install NPM dependencies
        run: pnpm install --prefer-offline --ignore-scripts

      - name: Run full suite
        run: pnpm run deploy

  build-apps:
    name: Build Docker apps images
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        type: [server, web]

    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: guusvanmeerveld
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build app image
        uses: docker/build-push-action@v3
        with:
          tags: |
            guusvanmeerveld/dust-mail:git-${{ matrix.type }}
            ghcr.io/guusvanmeerveld/dust-mail:git-${{ matrix.type }}

          push: true

          context: .
          file: apps/${{ matrix.type }}/Dockerfile

          platforms: linux/amd64,linux/arm64

          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-standalone:
    name: Build Docker standalone image
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: linux/amd64,linux/arm64

      - name: Setup Fly.io utility
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: guusvanmeerveld
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build standalone image
        uses: docker/build-push-action@v3
        with:
          tags: |
            guusvanmeerveld/dust-mail:git-standalone
            ghcr.io/guusvanmeerveld/dust-mail:git-standalone

          push: true

          context: .
          file: Dockerfile

          platforms: linux/amd64,linux/arm64

          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
