name: Publish Mail-Discover package to NPM

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/release-discover.yml
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS v12
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: "https://npm.pkg.github.com"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install

      - name: Build package
        run: yarn --cwd packages/mail-discover build

      - name: Publish package
        run: yarn --cwd packages/mail-discover publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
