name: "Build release"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-release.yml
    tags:
      - "v[0-9]+.*"

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  release_assets:
    name: Release assets
    needs: create_release

    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.61
          default: true
          override: true

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./packages/client/src-tauri

      - name: Install NPM dependencies
        run: yarn --cwd packages/client install

      - name: Fetch crates
        run: cd packages/client/src-tauri && cargo fetch --locked

      - name: Install dependencies (linux only)
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Build application
        run: yarn --cwd packages/client run tauri build
        env:
          VITE_DEFAULT_SERVER: ${{ secrets.CLIENT_DEFAULT_SERVER }}

      - name: Zip output
        uses: vimtor/action-zip@v1
        with:
          files: ./packages/client/src-tauri/target/release/bundle
          dest: ./bundle.zip

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: dust-mail-${{ matrix.config.os }}.zip
          asset_path: ./bundle.zip
          asset_content_type: application/zip
